name: 🪲 Bug Report
description: Create a report to help us fix issues.
labels: ["Type: bug"]

body:
- type: input
  attributes:
    label: Firmware version
    description: The firmware version where this bug occurs with.
    placeholder: V0.0.0
  validations:
    required: true
- type: textarea
  attributes:
    label: Description 
    description: What is the bug you are experiencing? 
    placeholder: |
      firmware crashes and stops the grinder
  validations:
    required: true
- type: textarea
  attributes:
    label: Reproduction steps
    description: Share what did you do, when this bug showed up, so we can reproduce it
    placeholder: |
      1. Power cycle the grinder
      2. Start the calibration process
  validations:
    required: true
- type: textarea
  attributes:
    label: Actual results
    description: What happens after the above steps have been followed?
    placeholder: |
      The firmware crashes and is unable to perform the grinding process.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected results
    description: What should happen after the above steps have been followed?
    placeholder: |
     The grinder should be ready to operate.
  validations:
    required: true
- type: dropdown
  id: reproducible
  attributes:
    label: Reproducible?
    description: Were you able to reproduce the issue (in contrast to only having experienced it once)?
    options:
      - "Yes"
      - "No"
      - "Haven't tried"
- type: textarea
  id: additional
  attributes:
    label: Additional information
    description: Is there anything else you can tell us about this bug?
- type: textarea
  id: logs
  attributes:
    label: Relevant log output
    description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
    render: shell
- type: textarea
  id: screenshots
  attributes:
    label: Screenshots
    description: If applicable, please share any relevant screenshots you might have.
